### ISSUE TITLE
I'm looking for a way to add "milter" library to a PASE, and after that "mussels".

### ISSUE THREAD

**Issue by Kuku-2021** [IBM/ibmi-oss-issues#11]
Hi, 
Someone have installed one of the two packages?
I can't find how to do it and it's important as part os a project.

**Comment by kadler** [comment]
This issue tracker is for issues with existing packages. If you're asking for new packages from IBM, you'll need to open an RFE. If you'd like to collaborate with the community, please check the Ryver forum ([links here](https://ibmi-oss-docs.readthedocs.io/en/latest/README.html#collaboration))
