### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas' in IBM I (AS400)

### ISSUE THREAD

**Issue by kapiltiwarimca** [IBM/ibmi-oss-issues#12]
Pandas is intalled but when i run the script , it ModuleNotFoundError: No module named 'pandas'.

I have installed everything by  IBM i client access solution open source package option.

i have  already set path in qp2term

PATH=/QOpenSys/pkgs/bin:$PATH
export PATH

Please advise

**Comment by kadler** [comment]
How are you running the script?

**Comment by kapiltiwarimca** [comment]
Hi kevin,

I am calling from Cl

PYONI/PYRUN2 +
             SCRIPTDIR('/home/kapilt/Production_Source') +
             SCRIPTFILE('RNW0001.py') PYVERSION(3) +
             PYPATH('/QOpenSys/pkgs/bin/') CCSID(37) +
             DSPSTDOUT(*YES) LOGSTDOUT(*NO) +
             PRTSTDOUT(*NO) DLTSTDOUT(*YES)

But it is also not working from QP2TERM .

**Comment by kapiltiwarimca** [comment]
Hi Kevin,

I am in a different timezone.

what time i  should  be online so that i can check and answer your
questions quickly .

Thanks,

Kapil

**Comment by ThePrez** [comment]
This is likely a scenario where you have `pandas` installed for a different version of Python than you are running. 
First off, when running outside of `PYRUN2`, it's good practice to explicitly qualify which Python version you would like to run, as documented at https://ibmi-oss-docs.readthedocs.io/en/latest/python/README.html 

PYRUN2, as documented [here](https://github.com/richardschoen/PythonOniLibrary), is rolled into the larger [QSHONI project](https://github.com/richardschoen/QShOni). PYRUN2 does not support Python3.9 explicitly. 

The recommendation is to either:
- Switch to `QSHPYRUN` and specify the `PYVERSION(3.9)` option
- Use a different technique for starting your script (for instance, QP2TERM, QSH, Service Commander, or your own wrapper commands)

**Comment by ThePrez** [comment]
The [QSHPYRUN documentation](https://github.com/richardschoen/QshOni) says that `PYVERSION(3.9)` is allowed. If it's not allowing `3.9` as a value, I would recommend opening an issue against that project, which I see you've already done
https://github.com/richardschoen/QshOni/issues/9 
Looks like an upgrade will give you what you need.
