### ISSUE TITLE
IBMi 7.4 repo is not getting rpm updates

### ISSUE THREAD

**Issue by andyf0x** [IBM/ibmi-oss-issues#13]
The [7.4 repo](https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo-7.4/ppc64/) isn't getting any of the recent rpm updates that were published to the [7.3 repo](https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo-7.3/ppc64/). It is missing the following rpm's: -

binutils-devel-2.37-1.ibmi7.3.ppc64.rpm
binutils-gnu-2.37-1.ibmi7.3.ppc64.rpm
gcc10-10.3.0-9.ibmi7.3.ppc64.rpm
gcc10-cplusplus-10.3.0-9.ibmi7.3.ppc64.rpm
gcc10-cpp-10.3.0-9.ibmi7.3.ppc64.rpm
gcc10-gfortran-10.3.0-9.ibmi7.3.ppc64.rpm
libatomic1-10.3.0-9.ibmi7.3.ppc64.rpm
libgcc_s1-10.3.0-9.ibmi7.3.ppc64.rpm
libgfortran5-10.3.0-9.ibmi7.3.ppc64.rpm
libgomp1-10.3.0-9.ibmi7.3.ppc64.rpm
libopenblas0-0.3.19-1.ibmi7.3.ppc64.rpm
libstdcplusplus6-10-devel-10.3.0-9.ibmi7.3.ppc64.rpm
libstdcplusplus6-10.3.0-9.ibmi7.3.ppc64.rpm
nodejs16-16.13.2-1.ibmi7.3.ppc64.rpm
openblas-devel-0.3.12-1.ibmi7.3.ppc64.rpm
openblas-devel-0.3.19-1.ibmi7.3.ppc64.rpm

**Comment by kadler** [comment]
The 7.4 repo has been synced up with the 7.3 repo. It should be available now; you may need to run `yum clean metadata` first, though.
