### ISSUE TITLE
New installation Python3.6 version

### ISSUE THREAD

**Issue by dthapar1088** [IBM/ibmi-oss-issues#16]
Hi, 

we installed python3.6 version on our IBm i partition 7.3 and starting with creating a hello World program, we have some issues as below 
python3.6                                                              
Could not find platform independent libraries <prefix>                 
Could not find platform dependent libraries <exec_prefix>              
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]               
Fatal Python error: Py_Initialize: Unable to get the locale encoding   
ModuleNotFoundError: No module named 'encodings'                       
                                                                       
Current thread 0x0000000000000001 (most recent call first):            
qsh: 001-0078 Process ended by signal 5.                               
$                                                                      
python3.6 -V                                                           
Python 3.6.15

**Comment by kadler** [comment]
Hi @dthapar1088 I cannot recreate this issue here.  Are you sure the package installed successfully? I would try running `rpm --verify python3` to make sure.

**Comment by ThePrez** [comment]
Also, please make sure you aren't running the definct 5733OPS Python (run `ls -l $(which python3`)

**Comment by dthapar1088** [comment]
HI, 

i Install below python packages 

python3-pip python3-ibm_db python3-itoolkit
 and could do Python form Qshell however when running other commands it struck on 1st initial of the command as given in the attachment 
![Python Error](https://user-images.githubusercontent.com/105925737/170998650-4531970c-cfde-4409-8fdf-69542c480973.PNG)

**Comment by dthapar1088** [comment]
Ok, now we installed other packages of Python3.9 python39-ibm_db and python39-itoolkit and we can call hello world program with this however it struck on 1 initial letter and then we need to press enter twice to come to some results,

**Comment by kadler** [comment]
This is a known issue. The REPL does not work in a 5250 session; you must use SSH for that instead.
