### ISSUE TITLE
curl not resolving host names

### ISSUE THREAD

**Issue by robinsg** [IBM/ibmi-oss-issues#19]
I have an isuues on one LPAR, when I try to run a curl command I get:

```
grobinso@xxxxast1:~ $ curl --proxy http://myproxy:11000 https://pypi.org
curl: (6) getaddrinfo() thread failed to start
```

If I use wget or pip with the same proxy server and url it works fine.

I'm running V7R3 with latest PTFs and RPMs:

```
grobinso@xxxxast1:~ $ uname -a
OS400 xxxxast1 3 7 007800012345
grobinso@xxxxast1:~ $ yum deplist curl
http://xxxxx-yyy-mgt01/repos/ibmi/repodata/repomd.xml: [Errno 14] curl#6 - "getaddrinfo() thread failed to start"
Trying other mirror.
http://xxxxx-yyy-mgt01/repos/ibm-7.3/repodata/repomd.xml: [Errno 14] curl#6 - "getaddrinfo() thread failed to start"
Trying other mirror.
Finding dependencies:
package: curl.ppc64 7.76.1-1
  dependency: lib:/QOpenSys/pkgs/lib/libcurl.so.4(shr_64.o)(ppc64)
   provider: libcurl4.ppc64 7.76.1-1
  dependency: lib:/QOpenSys/usr/lib/libc.a(shr_64.o)(ppc64)
   provider: pase-libs-dummy.fat 7.2-0
  dependency: lib:/QOpenSys/usr/lib/libpthreads.a(shr_xpg5_64.o)(ppc64)
   provider: pase-libs-dummy.fat 7.2-0
  dependency: libcurl4 = 7.76.1-1
   provider: libcurl4.ppc64 7.76.1-1
```
My IBM i DNS settings are consistent on all my LPARs, I used Ansible to set them up.

If I use curl to an internal URL it also fails so it's not a proxy server issue as I don't reference the proxy server for internal connections. However, on my other LPARs the curl command to the same internal URL works fine.

I've tried setting QIBM_MULTI_THREADED to Y and restarted SSHD but this doesn't make any difference.

Any ideas how i can troubleshoot this issue?

Thanks

**Comment by ThePrez** [comment]
First thought: perhaps the root cause is the same as https://github.com/halcyon-tech/vscode-ibmi/issues/678
Please try the resolution there

**Comment by robinsg** [comment]
Nope, that didn't work either.

**Comment by robinsg** [comment]
My apologies, that did work. . . I ran curl using a url behind a firewall.

It works fine now.

Thanks for your assistance.
