### ISSUE TITLE
git subtree is not a command

### ISSUE THREAD

**Issue by robinsg** [IBM/ibmi-oss-issues#20]
git version 2.26.2

I use git subtree ina repo which I have just cloned to my IBM i LPAR.

However, when I try and use git subtree pull/push I get a message saying:

`git: 'subtree' is not a git command. See 'git --help'.`

Is there a way for me to get the git subtree command for IBM i?

**Comment by kadler** [comment]
Looks like git-subtree is a contrib extension that we don't package. It's just a shell script, so as a workaround you could download and install it manually:

```
curl --output /QOpenSys/pkgs/libexec/git-core/git-subtree https://raw.githubusercontent.com/git/git/v2.26.2/contrib/subtree/git-subtree.sh
chmod 755  /QOpenSys/pkgs/libexec/git-core/git-subtree
```

No clue if it works on IBM i, but a cursory glance seems to look ok. Let me know what you find out if you test it.

**Comment by robinsg** [comment]
Well, this works on IBM i.

First run it complained about "<: unknown test operator".

So I modified the shebang from:

/bin/sh
TO
/bin/bash

and it worked.

Is this the best approach or should/could I do something different to get the code to work without modification?

Thanks
Glenn

**Comment by kadler** [comment]
As part of the git build, the shebang line would have been changed to `/QOpenSys/pkgs/bin/bash` so your change is fine. My guess is they have some bash-isms in there, which is why we set the git shell to bash in the first place.

**Comment by robinsg** [comment]
I did consider using /QOpenSys/pkgs/bin/bash at first but when I saw /bin/bash was a link to it I thought it best to use that.

Thanks a lot for you help.

Any chance this can be integrated in to the IBM i git package?
