### ISSUE TITLE
profound js

### ISSUE THREAD

**Issue by Dmaynard1961** [IBM/ibmi-oss-issues#22]
I am setting up PROFOUNDJS and need to to use HTTPS
"sslKey": "/my_cert/key.pem",
"sslCert": "/my_cert/cert.pem"
there are two statements that i have to use a KEY an CERT.

The link pointed me to https://nodejs.org/dist/latest-v10.x/docs/api/tls.html#tls_tls_createsecurecontext_options
but i am not sure where and how to get these two files

**Comment by kadler** [comment]
Sounds like you figured it out based on #23. Can we close this issue then?

**Comment by Dmaynard1961** [comment]
Nothing is fixed yet.  I cannot get it to work.  I actually tried with exporting all the certificates



***@***.***

Don Maynard
Analyst

Contrans Corp.
Tel.: 416-419-7769
Mob.: 416-419-7769
http://www.contrans.ca<https://www.contrans.ca/>

***@***.***
