### ISSUE TITLE
NODE.JS

### ISSUE THREAD

**Issue by Dmaynard1961** [IBM/ibmi-oss-issues#23]
I am trying to setup SSL to use with NODE.JS and followed the instructions on this document
https://www.ibm.com/support/pages/how-extract-ssltls-certificates-digital-certificate-manager-dcm-and-use-them-openssl-ibm-i-os

when i try to access i get privacy error,and  net::err_cert_common_name_invalid

i am not sure how to fix this

**Comment by kadler** [comment]
AFAICT, this is a client issue (net::err_cert_common_name_invalid is a Chrome error). Sounds like your SSL certificate's common name is set to a different hostname than what you're connecting to. Are you trying to connect to the IP address instead of the hostname or vice-versa? Maybe try some of the steps here: https://www.hostinger.com/tutorials/net-err_cert_common_name_invalid (first search hit for the error).

**Comment by Dmaynard1961** [comment]
I am at a loss,   I am extracting the   Certificate from the AS400 DCM,   and then running some openssl commands  but each time I get this same error

Am I missing something on the AS400 DCM       There are six certificates listed    I used the latest one created





***@***.***

Don Maynard
Analyst

Contrans Corp.
Tel.: 416-419-7769
Mob.: 416-419-7769
http://www.contrans.ca<https://www.contrans.ca/>

***@***.***

**Comment by kadler** [comment]
Sounds like you should talk to your sysadmin or whoever is in charge of your SSL certificates to see which one you should use.

**Comment by kadler** [comment]
Does the system have SSL enabled for other services already? If so, the certificate must be in DCM.

Alternatively, you _may_ be using the right certificate but using the wrong hostname to browse to it. The URL you connect to must match the Common Name in the certificate. You can view the Common Name using the openssl command, eg. `openssl x509 -noout -subject -in /path/to/cert.pem`; the Common Name follows the CN abbreviation.

**Comment by Dmaynard1961** [comment]
Okay   I have two extracts from  DCM

One has no common name after the  CN

The other has  *.contrans.ca

In config.js file   the SSLKEY and SSLCERT point to the  *.contrans.ca

So I used url   https://contrans.contrans.ca:8072

I know I will be asked but how can I use  https://contrans:8072



***@***.***

Don Maynard
Analyst

Contrans Corp.
Tel.: 416-419-7769
Mob.: 416-419-7769
http://www.contrans.ca<https://www.contrans.ca/>

***@***.***
