### ISSUE TITLE
Git cloning issue

### ISSUE THREAD

**Issue by tomcphr** [IBM/ibmi-oss-issues#28]
I've installed Git using yum.  I've got the latest git version and the latest version of ibmi-base etc.

I'm trying to clone a repository and I get this error.
```
error: unable to mmap '/home/{username}/{repo_name}/.git/config': No such device
fatal: could not set 'core.filemode' to 'true'
```

How can I fix this?

**Comment by epgmat** [comment]
The issue occurs when your folder is journaled. See IBM docs: https://www.ibm.com/docs/en/i/7.4?topic=ssw_ibm_i_74/apis/mmap.html

"_Journaling cannot be started while a file is memory mapped. Likewise, a journaled file cannot be memory mapped. The mmap() function will fail with ENOTSUP if the file is journaled._"
