### ISSUE TITLE
system and cl utilities not working in chroot

### ISSUE THREAD

**Issue by robinsg** [IBM/ibmi-oss-issues#30]
My chroot is installed with minimal and includes .lst files.

If I go in to the the chroot and run:

```
system "wrksyssts"
```
nothing is returned to the session display.

When I run the same but with cl I get:

```
cl "wrksyssts"
CPD000D: Command *LIBL/WRKSYSSTS not safe for a multithreaded job.
```

If I exit out of the chroot these commands work as expected.

What do I need to use these utilities in my chroot?

**Comment by kadler** [comment]
AFAIK nothing can be done there because the chroot does not have access to /QSYS.LIB. @ThePrez @abmusse do you know any solutions?

**Comment by robinsg** [comment]
OK, understood.
Thank you.
