### ISSUE TITLE
IBM ACS Open Source package manager -- broken

### ISSUE THREAD

**Issue by mikebohlen** [IBM/ibmi-oss-issues#31]
I was updating some of my open source packages and lost connectivity during some of them.  I now have 2 entries in the list one with a version and one saying installed.  I have also tried using yum to fix it up with no luck and now when I try and use YUM to list the repolist I get this:

system@development:~$ yum repolist
ftp://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo/repodata/repomd.xml: [Errno 14] FTP Error 550 - Access denied: 550
Trying other mirror.
repo id                                      repo name                                                       status
ibm                                          ibm                                                             0
ibmi-base                                    IBM i base                                                      0
ibmi-release                                 IBM i 7.4                                                       0
rpms.sobo.red_ibmi_                          added from: http://rpms.sobo.red/ibmi/                          0
repolist: 0

**Comment by kadler** [comment]
That is for the old repo file. Please refer to https://ibmi-oss-docs.readthedocs.io/en/latest/yum/IBM_REPOS.html#what-should-i-do-with-the-existing-ibm-repo-file

Note that the IBM download server no longer supports FTP, which is why you're getting this error message now.

**Comment by mikebohlen** [comment]
Yep, that took care of the repo connection, now just need to fix the entries that are duplicated and say installed, this happened when I was updating some packages and it hung until it eventually timed out

**Comment by mikebohlen** [comment]
already tried yum-complete-transaction

**Comment by mikebohlen** [comment]
I can not reinstall or remove

**Comment by mikebohlen** [comment]
Also, this seems to be happening more freq. I now have 2 more lpars where packages hang during Update and it appears random, where it can happen to any package.

**Comment by mikebohlen** [comment]
Thanks that helped -- all fixed up
