### ISSUE TITLE
Trying to run Python program on IBM i 7.1

### ISSUE THREAD

**Issue by josys36** [IBM/ibmi-oss-issues#32]
On IBM i 7.3 I created a virtual environment of Python 3.9 in a specific directory. I put a simple python program in there, and was able to run the program using the virtual environment. When I moved the virtual environment to IBM i 7.1 it will not run. I keep getting the following error,

Dependent module libpython3.9.so could not be loaded.

I cannot tell if this is a path issue or?? In the environments that this python would be ran, the customer may not have open source tools installed at all. I was under the understanding that a Python virtual environment would contain everything needed.

Jason

**Comment by kadler** [comment]
The virtual environment does not contain everything that is needed, it still relies on the Python packages and library (eg. libpython3.9.so) that are installed by the Python rpm. You will need to install the Python 3.9 package on the system where you are running it, however you cannot install Python 3.9 package on IBM i 7.1 as our packages are built on IBM i 7.3 and packages are not forward compatible.

IBM i 7.1 is not supported by the open source team (never was officially supported), nor is IBM i 7.2 any longer either. You must upgrade to IBM i 7.3 or newer to get any new software or package updates.

**Comment by josys36** [comment]
Ok so can the install of the open source packages be automated during a software install? I know I'm going to be asked. In many cases I won't have any control over the environment where this is going to be used.

**Comment by kadler** [comment]
> during a software install

What kind of install do you mean?

**Comment by josys36** [comment]
I mean if I install my own custom written software on an IBM i, can I also automate the install of the open source software products such as Python? That would be if it's not installed.

**Comment by kadler** [comment]
If you can call `yum install` from your install, sure. If the bootstrap is not installed, you can use the manual bootstrap instructions first: https://ibmi-oss-docs.readthedocs.io/en/latest/yum/README.html#offline-install-instructions-without-acs
