### ISSUE TITLE
Repo Access Denied

### ISSUE THREAD

**Issue by lawsonkyle** [IBM/ibmi-oss-issues#35]
We are on 7.3, but have not installed the ibmi-release and ibmi-base repos.  I am getting an FTP Error 550.  

yum install ibmi-release ibmi-base
ftp://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo/repodata/repomd.xml: [Errno 14] FTP Error 550 - Access denied: 550

Not sure how to get around this.

**Comment by kadler** [comment]
Edit /QOpenSys/etc/yum/repos.d/ibm.repo and change ftp to https. You will need to have the ca-certificates-mozilla package installed.

**Comment by lawsonkyle** [comment]
I have tried to install the ca-certificates-mozilla package but I get the same problem.

Downloading Packages:
ftp://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo/noarch/ca-certificates-2_git20170807.10b2785-3.ibmi7.2.noarch.rpm: [Errno 14] FTP Error 550 - Access denied: 550
Trying other mirror.

**Comment by kadler** [comment]
Yes, if you do not have ca-certificates-mozilla installed, then you have to go through a different process.

You'll need to change the repo to https and then add the line `sslverify=0`. Once you have that set up, install ca-certificates-mozilla, then remove the `sslverify=0` line.

**Comment by lawsonkyle** [comment]
I got that cleared up and ibmi-repos installed.  Thank you for the help
