### ISSUE TITLE
Auto Start Node-Red?

### ISSUE THREAD

**Issue by jeffg324** [IBM/ibmi-oss-issues#4]
Hi, I set up the Node-Red Dashboard example (Thank you Matt!) and I'm sure I'm missing something easy....... how do you auto start node-red without signing into SSH? I would like to have it start anytime the system restarts with my intervention, maybe submit a job with STRQSH?

**Comment by ThePrez** [comment]
@jeffg324 , I think this is resolved, but feel free to reopen if you need more assistance. @thebeardedgeek , thanks for the help!
