### ISSUE TITLE
Copy and Paste in tmux

### ISSUE THREAD

**Issue by robinsg** [IBM/ibmi-oss-issues#44]
I have tmux installed and I'm trying to use the mouse to copy and paste between the tmux session and the system clipboard.

From what I'm reading online it suggests that I need to install xclip but that's not available in the repos.

Any suggestions on how I can do this in a PASE session?

**Comment by kadler** [comment]
We do not have xclip (or xsel as I've seen suggested also). I don't think there's any way to do that in PASE currently.
