### ISSUE TITLE
Cannot install node-red-contrib-db2-for-i and node-red-dashboard on IBMi

### ISSUE THREAD

**Issue by MD2706GIT** [IBM/ibmi-oss-issues#5]
Hello.
I successfully installed Node-red; from the menu "Manage palette" -> Install, I tried to install **node-red-contrib-db2-for-i** and **node-red-dashboard** but both installations fail. It appears it fails installing idb-connector. I also tried manually installing idb-connector from an SSH session, but it keeps failing.
Could you please advise on how can I solve ?
Thank you !

Here the log:
[2020-12-04T10_51_53_880Z-debug.log](https://github.com/IBM/ibmi-oss-examples/files/5642231/2020-12-04T10_51_53_880Z-debug.log)

**Comment by ThePrez** [comment]
Closing as I believe this is resolved. Please reopen if you need further assistance. Thanks!
