### ISSUE TITLE
Nodejs18 failed 001-0078 Process ended by signal 5

### ISSUE THREAD

**Issue by adgomezgbm** [IBM/ibmi-oss-issues#53]
We are working automation projects with Nodejs18 on the IBMi. In development system works without problems, but when pass to QA system fail wi the error “001-0078 Process ended by signal 5” with each NodeJs command executed.
We validate both systems environment (Development and QA): PTFs, environment variables, language, CCSID, etc. and we were unable to determine the problem.
QIBM_MULTI_THREADED=Y is configured, we re-installed the nodejs18 package with GUI interface.

What other values can we review to solve the issue?
Thanks for any help you can give us.

**Comment by kadler** [comment]
> Open source should be run from an SSH terminal and not from a 5250 session

Except in the case of batch programs, which need to use QSH on the SBMJOB.

We do have a FAQ entry for this: https://ibmi-oss-docs.readthedocs.io/en/latest/troubleshooting/README.html#commands-are-failing-in-qsh However, QIBM_MULTI_THREADED=Y is said to be configured, so that should have solved it.

How are you running these applications which are failing? Are you running interactively or through SBMJOB or what? If you are using SBMJOB are you using ALWMLTTHD(*YES)?

**Comment by adgomezgbm** [comment]
Thanks for your comments 
We ran SSH environment, show the next error:
`$node -v
Could not load program node:
rtld: 0712-001 Symbol RSA_get0_pss_params was referenced
      from module node(), but a runtime definition
            of the symbol was not found.
rtld: 0712-002 fatal error: exiting.
$`

When try the SBMJOB with ALWMLTTHD(*YES), the joblog show:
`                                   Message . . . . :  -QSH CMD('node -v')
QSH0005    Completion              00   01/31/24  16:04:08.828084  QZSHRUNC     QSHELL      *STMT    QCMD        QSYS        01C8
                                     From module . . . . . . . . :   QZSHRUNC
                                     From procedure  . . . . . . :   main
                                     Statement . . . . . . . . . :   149
                                     Message . . . . :   Command ended normally with exit status 133.`

The QP0ZSPWT job log show:
`Message . . . . :   No runtime definition found for symbol
                                       RSA_get0_pss_params.
                                     Cause . . . . . :   The symbol was referenced from PASE for i module node, but
                                       no runtime definition of the symbol was found. The error occurred attempting
                                       to load PASE for i program node. Recovery  . . . :   Correct the error and
                                       then try the request again.`

and the ouput of the command: 
`qsh: 001-0078 Proceso finalizado por la señal 5.`

**Comment by kadler** [comment]
Sounds like https://github.com/IBM/ibmi-oss-issues/issues/9 Can you try upgrading libopenssl1_1?

**Comment by adgomezgbm** [comment]
@kadler Thanks, upgrade the package and solved the issue.
