### ISSUE TITLE
Open Source install and configure

### ISSUE THREAD

**Issue by praveenhb-hcl** [IBM/ibmi-oss-issues#58]
Hi Team,

We are planning to install the Opensource Repositories supported by IBM. There are couple of question related to the IBM Open-Source Repositories only: we are concentrating only on the IBM Open-Source Repositories only:

1) How can we take the backup and what needs to be backed up once the IBM open-Source Repositories has been installed?

2) In case if we need to revert back to the previous version, how do we revert back?

For example, the current version is X.X.0.1 we have upgraded the version to X.X.0.2. unfortunately, we get into some issues, and we need to revert back to the X.X.0.1 version. 

Regards,

Praveen.

**Comment by praveenhb-hcl** [comment]
Hi,

Can anyone assist us on the above queries?

Regards,
Praveen.

**Comment by kadler** [comment]
>     1. How can we take the backup and what needs to be backed up once the IBM open-Source Repositories has been installed?

For the most part, packages are only installed under /QOpenSys/pkgs so backing that up gets you 99% of everything. There's also some stuff in /QOpenSys/var and /QOpenSys/etc, but you would need to look at individual packages and what they are using.

>     2. In case if we need to revert back to the previous version, how do we revert back?

There is a mechanism to revert to an older package using `yum downgrade`, however we typically only keep the latest versions of packages on the repository to save space. If you want to have consistent downgrades, you'll need to keep local copies of the repo, eg. with the ACS [clone repo tool](https://ibmi-oss-docs.readthedocs.io/en/latest/acscloner/README.html)

**Comment by praveenhb-hcl** [comment]
Classification: Confidential
Hi,

Is there any possibility that we can individually select the repository which we need to backup.

Regards,
Praveen.

**Comment by kadler** [comment]
I don't know what you mean by backing up a repository. If you're talking about the clone tool, that works on individual repositories so you already have a means to pick which repos you want. Do you mean something else?

**Comment by praveenhb-hcl** [comment]
Classification: Confidential
Hi Team,

When we tried to clone the repository, we got the below error message:

***@***.***

***@***.***

***@***.***

Can you please check and advice on how to proceed further.

Regards,
Praveen.

**Comment by praveenhb-hcl** [comment]
Classification: Confidential
Hi Team,

When we tried to clone the repository, we got the below error message:

***@***.***

***@***.***

***@***.***

Can you please check and advice on how to proceed further.

Regards,
Praveen.

**Comment by kadler** [comment]
Sorry @praveenhb-hcl but I don't see any error messages in your response. Maybe your email server is stripping it out? Can you please post it using the web interface? (the email reply also adds a bunch of extra clunky, email-y noise as it is)

**Comment by praveenhb-hcl** [comment]
Hi Team,

I have uploaded the files now.

Regards,
Praveen.
![Capture1](https://github.com/IBM/ibmi-oss-issues/assets/173052712/5fc2c5e9-49dc-48c7-bcc3-320ed71c35f5)
![Capture2](https://github.com/IBM/ibmi-oss-issues/assets/173052712/c4fd2454-4b96-43e3-a517-58b85a764a70)
![Capture3](https://github.com/IBM/ibmi-oss-issues/assets/173052712/598685bb-bdcb-4508-be39-ff99be0d0c2f)
![Capture4](https://github.com/IBM/ibmi-oss-issues/assets/173052712/985b5119-62ca-47f9-be00-7d047bcfea5d)
![Capture5](https://github.com/IBM/ibmi-oss-issues/assets/173052712/278c7e73-a577-4c98-a15e-109816d74e26)

**Comment by praveenhb-hcl** [comment]
Classification: Confidential
Hi Team,

I have replied in the web interface.

Regards,
Praveen.

**Comment by kadler** [comment]
> I have replied in the web interface.

Thanks, I saw that already.

**Comment by kadler** [comment]
Not exactly sure what the problem is, but is there a reason you are using the old repo? FYI that repo is no longer updated and you should use the repo-base-7.3.

As to the issue, unless @ThePrez has any quick ideas, you may need to contact IBM support since that is part of ACS and not under our control here.

**Comment by praveenhb-hcl** [comment]
Classification: Confidential
Hi Korinne Adler,

Thank you very much for the response.

However, I have couple of queries for the below 3 OSS:

OSS:


  1.  coreutils
  2.  filesystem-dummy
  3.  Pip3

For coreutils, I did find in the IBM link below, but its not showing in out ACS - Open source package.
https://www.ibm.com/support/pages/aix-toolbox-open-source-software-downloads-alpha

However, could you please also let us know where can we find the downloads software package for the below:

Filesystem-dummy
Pip3

Regards,
Praveen.

**Comment by kadler** [comment]
> For coreutils, I did find in the IBM link below, but its not showing in out ACS - Open source package.
https://www.ibm.com/support/pages/aix-toolbox-open-source-software-downloads-alpha

That package has nothing to do with ours. You should not attempt to run AIX software on IBM i.

> However, could you please also let us know where can we find the downloads software package for the below:

What do you mean? The software is installed via ACS or yum. You should not need to download it manually at all.

**Comment by praveenhb-hcl** [comment]
Hi Kadler,

Thank you very much for the response.

However, I have attached the screenshot for your reference where you are able to see the OSS which is available in IBM website.

Can you please guide us on how to download the "coreutils" as this is not available in our ACS repository.

Regards,
Praveen.
![Capture11](https://github.com/IBM/ibmi-oss-issues/assets/173052712/d211e482-115b-4fcd-b53e-b0a839122589)
![Capture12](https://github.com/IBM/ibmi-oss-issues/assets/173052712/9288f76d-e367-410c-b844-4e4e3034c0c8)

**Comment by kadler** [comment]
The second screenshot you provided is for the AIX Toolbox, which is not applicable to IBM i and PASE. If you have questions about that, you need to talk to the AIX team. IBM is a large company with a lot of different offerings, just because it is available on the IBM website doesn't mean it's applicable to this product.

As to how to get GNU coreutils on IBM i, that is available as the "coreutils-gnu" package. Package names for IBM i can and many times are different than the AIX package names.

**Comment by praveenhb-hcl** [comment]
Classification: Confidential
Hi Team,

I have a question:

For example, we have installed Python OSS from the Opensource package available and its been started using it. Considering this, do you know what will would be the resource utilization for the jobs associated with it and how can we measure the utilization on the associated jobs and where can we check for the jobs associated with it and what would be the jobs names?

Regards,
Praveen.

**Comment by kadler** [comment]
Resource utilization will vary based on what you do with it. Finding the job name is not particularly easy at the moment. If you are using bash shell you can use the `getjobid` builtin to determine the shell's job name. The job name for your python job will be similar to that and in the same subsystem.

**Comment by praveenhb-hcl** [comment]
Classification: Confidential
Hi,

Once the OSS is installed and  If we need to monitor something to keep it running for example if these would require some jobs, etc to keep running? What would be the requirement?

Regards,
Praveen.

**Comment by kadler** [comment]
That is too vague a question to answer. If you have specific followup questions, those would be better asked in our Ryver community: https://ibmi-oss-docs.readthedocs.io/en/latest/README.html#collaboration

**Comment by praveenhb-hcl** [comment]
Classification: Confidential
Hi Team,

I have skipped couple of email from the past and replying to one of the email.

I have got few question. We have installed the below OSS in one of our LPAR:

OSS
Ansible
bash
bzip2
ca-certificates
charset-aliases
chsh
coreutils
curl
db
db2util
dos2unix
file
file-magic
filesystem-dummy
findutils
gawk
git
grep-gnu
gzip
ibmi-repos.noarch
iconv-gnu (core)
joe
jq
less
man-db
mc
nano
openssl
pigz
Pip3
python3
python39
python3-ibm_db
python3-itoolkit
rpm
sed-gnu
tar-gnu
tree
unixODBC
update-alternatives
vim
wget
yum
zip

However, we need to know if there are any updates in the installed packages or any bug fix or any kind of major fixes, then, how can we come to know on this?

Regards,
Praveen.

**Comment by praveenhb-hcl** [comment]
Classification: Confidential
Hi Team,

I have got few question. We have installed the below OSS in one of our LPAR:

OSS
Ansible
bash
bzip2
ca-certificates
charset-aliases
chsh
coreutils
curl
db
db2util
dos2unix
file
file-magic
filesystem-dummy
findutils
gawk
git
grep-gnu
gzip
ibmi-repos.noarch
iconv-gnu (core)
joe
jq
less
man-db
mc
nano
openssl
pigz
Pip3
python3
python39
python3-ibm_db
python3-itoolkit
rpm
sed-gnu
tar-gnu
tree
unixODBC
update-alternatives
vim
wget
yum
zip

However, we need to know if there are any updates in the installed packages or any bug fix or any kind of major fixes, then, how can we come to know on this?

Regards,
Praveen.


::DISCLAIMER::
________________________________
The contents of this e-mail and any attachment(s) are confidential and intended for the named recipient(s) only. E-mail transmission is not guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or may contain viruses in transmission. The e mail and its contents (with or without referred errors) shall therefore not attach any liability on the originator or HCL or its affiliates. Views or opinions, if any, presented in this email are solely those of the author and may not necessarily reflect the views or opinions of HCL or its affiliates. Any form of reproduction, dissemination, copying, disclosure, modification, distribution and / or publication of this message without the prior written consent of authorized representative of HCL is strictly prohibited. If you have received this email in error please delete it and notify the sender immediately. Before opening any email and/or attachments, please check them for viruses and other defects.
________________________________

**Comment by kadler** [comment]
You can view available updates through the Updates tab in the ACS Open Source Package Manager GUI or by running `yum list updates`.

If you have further questions please ask in our community channels or open a new issue.
