### ISSUE TITLE
isql command Japanese is cut off in the output of unixODBC isql

### ISSUE THREAD

**Issue by maokit** [IBM/ibmi-oss-issues#6]
When I output Japanese with isql, it cuts off in the middle
The � in the output below is displayed because DBCS is dead.
Is it inevitable that Japanese will be cut off?

`
SQL> select TKNAKJ from QEOL.TOKMSP
+---------------------+
| TKNAKJ              |
+---------------------+
| 阿井旅館　　�|
| 阿井工業　　�|
| 相川工業　　�|
| 阿井旅行社　�|
| 阿井食品Ｋ．�|
| 阿井自動車　�|
...
`

By the way, if you CAST and increase the column size, it will be output correctly.
I think it is a problem of buffer expansion when converting from Japanese to UTF-8, but can any settings improve it?

`
SQL> select CAST(TKNAKJ AS CHAR(24)) from QEOL.TOKMSP
+-------------------------+
| 00001                   |
+-------------------------+
| 阿井旅館　　　　|
| 阿井工業　　　　|
| 相川工業　　　　|
| 阿井旅行社　　　|
| 阿井食品Ｋ．Ｋ　|
| 阿井自動車　　　|
...
`

Below is the environment information.
**IBM i Version :** IBM i V7R3

**bash-4.4$ locale**
LANG=JA_JP.UTF-8
LC_COLLATE="JA_JP.UTF-8"
LC_CTYPE="JA_JP.UTF-8"
LC_MONETARY="JA_JP.UTF-8"
LC_NUMERIC="JA_JP.UTF-8"
LC_TIME="JA_JP.UTF-8"
LC_MESSAGES="JA_JP.UTF-8"
LC_ALL=JA_JP.UTF-8

**bash-4.4$ isql --version**
unixODBC 2.3.4

**bash-4.4$ cat odbcinst.ini**
[IBM i Access ODBC Driver]
Description=IBM i Access ODBC Driver
Driver=/QOpenSys/pkgs/lib/libcwbodbc.so
Threading=0
DontDLClose=1
UsageCount=1

**bash-4.4$ cat odbc.ini**
[*LOCAL]
Description = Default IBM i local database
Driver     = IBM i Access ODBC Driver
System     = localhost
UserID     = *CURRENT
CCSID      = 1208

**Comment by kadler** [comment]
> Isn't the column size * 6 in unixODBC?

It is up to the application to bind a large enough buffer to store the data. For isql, I believe it uses the buffer size directly, since it's a simple sample application.

Is your goal to use isql/iusql or to use PHP? Because if the problem is in PHP, then that has nothing to do with unixODBC and you're better opening an issue with Seiden Group or Zend/Perforce or at bugs.php.net, wherever you get your PHP from.

**Comment by kadler** [comment]
FYI, we did put some changes in to the driver for better handling of variable-length data from PHP. This may help isql as well.

The new driver should be released soon.
