### ISSUE TITLE
Installing Open Source Environment

### ISSUE THREAD

**Issue by NicholasRicher** [IBM/ibmi-oss-issues#60]
I’m running into issues when trying to install Open Source Package Management tools on my Power 10.

I’ve been following this guide: [Getting started with Open Source Package Management in IBM i ACS](https://www.ibm.com/support/pages/getting-started-open-source-package-management-ibm-i-acs)

I login to STRTCPSVR *SSHD, and then in ACS I go to “Open Source Package Management”.
Then I get this error message printed in ACS: Error: bsh: /QOpenSys/pkgs/bin/yum: not found

![image](https://github.com/user-attachments/assets/2748384e-1193-4068-a051-7b5417ac7a47)

So then next, following this guide https://ibmi-oss-docs.readthedocs.io/en/latest/troubleshooting/SETTING_PATH.html I adjusted my PATH to the "Best" option /QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin and now I get this error

![image](https://github.com/user-attachments/assets/9c5828cc-b358-499d-a41b-7d271ea06bb4)

The MSGGEN003 error message was mentioned in the guide I’m following (linked above or here [IBM i ACS Open Source Package Management Auth Fail Error](https://www.ibm.com/support/pages/node/1167988)). It says that the cause is that “The OpenSSH authentication mechanism on IBM i OS has extra environment items that can cause this issue.”

So now I’m on Step 2 of the Auth Fail Error guide:

Add the line, 
"ibmpaseforienv PASE_USRGRP_LIMITED=N" 
to the sshd_config file.  
A default location for this file is "/QOpenSys/QIBM/UserData/SC1/OpenSSH/etc/sshd_config

So I logged into 5250 Emulator as QSECOFR and used the following command to add the line as instructed: 
EDTF ‘/QOpenSys/QIBM/UserData/SC1/OpenSSH/etc/sshd_config’
Then I save and exit.

But I still get the same error message in ACS even after restarting the SSH server.

**Comment by kadler** [comment]
What IBM i version are you on? If you're on 7.4 or later, `PASE_USRGRP_LIMITED=N` is not needed (and I wouldn't recommend using ibmpaseforienv for that anyway).

**Comment by NicholasRicher** [comment]
I'm on 7.5. After I removed `ibmpaseforienv PASE_USRGRP_LIMITED=N` from my sshd_config, waited for around 15 minutes and tried again I got the first error again, but now I'm getting the second error.

**Comment by kadler** [comment]
Yeah on 7.5, you definitely shouldn't need the PASE_USRGRP_LIMITED, since that's the default. I have no idea why adding it would have broken anything, though.

Additionally, the PATH adjustment shouldn't be needed for the ACS package manager, but I don't think that should break anything. If yum can't be found then that would indicate the bootstrap is not installed, but then it should detect this and offer to install it for you. For either issue, you're going to have to open a ticket with IBM service to investigate further, since the issue is with ACS.

**Comment by NicholasRicher** [comment]
I've been trying to install this on an IBM i OS partition on my Power 10 but I just had a thought. Do you know if it has to be a Linux partition?

**Comment by kadler** [comment]
No, using a Linux partition makes no sense.

**Comment by alanseiden** [comment]
@NicholasRicher Can this issue be closed? (I heard it was resolved.)

**Comment by NicholasRicher** [comment]
@alanseiden Yes. Thank you.
