### ISSUE TITLE
need assistance with resolving duplicates

### ISSUE THREAD

**Issue by bhunsicker1** [IBM/ibmi-oss-issues#61]
I seem to have gotten a couple of packages installed twice.  
$ yum upgrade curl
Setting up Upgrade Process
Resolving Dependencies
There are unfinished transactions remaining. You might consider running yum-complete-transaction first to finish them.
--> Running transaction check
---> Package curl.ppc64 0:8.4.0-2 will be updated
---> Package curl.ppc64 0:8.6.0-1 will be an update
--> Processing Dependency: libcurl4 = 8.6.0-1 for package: curl-8.6.0-1.ppc64
--> Running transaction check
---> Package libcurl4.ppc64 0:8.4.0-2 will be updated
---> Package libcurl4.ppc64 0:8.6.0-1 will be an update
--> Processing Conflict: libcurl4-8.6.0-1.ppc64 conflicts python2 < 2.7.18-7
--> Finished Dependency Resolution
Error: libcurl4 conflicts with python2-2.7.18-6.ppc64
 You could try using --skip-broken to work around the problem
** Found 2 pre-existing rpmdb problem(s), 'yum check' output follows:
ibmi-repos-7.3-5.noarch is a duplicate with ibmi-repos-7.3-4.noarch
python2-2.7.18-7.ppc64 is a duplicate with python2-2.7.18-6.ppc64

The yum yum-complete-transaction - is that available for IBMi?   I tried that and it did not find that.   The yum-utils package is installed. 
I have tried to re-install,upgrade the duplicates, but I have received similar errors as above.   I did try the --skip-broken and it still had the same error as above.   

any suggestions?

**Comment by abmusse** [comment]
>The yum yum-complete-transaction - is that available for IBMi? I 

Yes it is 

```
yum-utils-1.1.31-9.noarch : Utilities for the yum package manager
Repo        : ibmi-base
Matched from:
Filename    : /QOpenSys/pkgs/bin/yum-complete-transaction
```

The issue you are running into is that you want to upgrade curl but that conflicts with the python2 you currently have installed.


```
# From the curl spec file

# Conflict with versions of Python 2 that are linked with -brtl.
# Otherwwise, yum will crash due to symbol conflicts between OpenSSL 1.1 used
# by the ssl module and OpenSSL 3 now used by curl.
Conflicts: python2 < 2.7.18-7
```

Please read why this conflicts was put into place: https://ibmi-oss-docs.readthedocs.io/en/latest/yum/OPENSSL3_MIGRATION.html

I believe the solution would be to update python2 first. Then you should be able to update curl.

CC

@kadler

**Comment by bhunsicker1** [comment]
Thanks.   We got the python2 resolved and was able to upgrade curl

**Comment by kadler** [comment]
Yeah, I wish yum would have automatically resolved the issue, but glad you were able to get it working.
