### ISSUE TITLE
iPerf on IBM i

### ISSUE THREAD

**Issue by zouhair-oulli** [IBM/ibmi-oss-issues#63]
Hello, I would like to inquire whether the iPerf tool is available on IBM i. I have installed related libraries, but I haven't been able to locate the package itself. This tool would be very helpful for me to measure network bandwidth and performance across multiple partitions.

These are the libraries I have installed on my IBM i partition :
![image](https://github.com/user-attachments/assets/cbd55971-9f88-4ccb-9bd5-c32c322aec62)

Related to iPerf, this is what I found on the [RPM packages repository](https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo-base-7.3/ppc64/) :
![image](https://github.com/user-attachments/assets/1e6a7dab-9ff7-4c98-aa66-64602232f4d5)

Do you have any idea ?
Thank you,

**Comment by kadler** [comment]
No, the libiperf packages are from https://github.com/IBM/portlibfori/tree/main/perfstat and is in no way related to the iPerf tool, which we do not have. If you'd like to request we add it, please open an Idea here: https://ideas.ibm.com/new-idea?product=7070565843208135910&category=7078724380260871338

**Comment by zouhair-oulli** [comment]
Thank you for your answer and suggestion. I have created an idea : https://ideas.ibm.com/ideas/IBMI-I-4245

**Comment by kadler** [comment]
Thanks. We'll take it under advisement.
