### ISSUE TITLE
curl does not work the same way when ran from a QSH or ssh session compared when ran as a QSH command

### ISSUE THREAD

**Issue by MarcRauzier** [IBM/ibmi-oss-issues#7]
I want to download files from IBM site (PTFs ISO file) using curl from an IBM i partition through a proxy server using sftp. It work fine when initiate the curl command from an interactive QSH or ssh session. But it does not work when I embed the curl command in QSH.

Maybe this is a shell syntax issue but I cannot figure where is my error.

Here is the output of curl command when ran through an **ssh or QSH session**:

```
  $                                                                                                                                
> curl --insecure --proxy "129.39.133.102:8080" --user "B80S63:blabla" --verbose --url sftp://delivery01-bld.dhe.ibm.com/GI/C/ftp1084_1.txt --output /home/fr076064/temp/ftp1084.txt
  *   Trying 129.39.133.102:8080...                                                                                                
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                  
                                   Dload  Upload   Total   Spent    Left  Speed                                                    
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  * Connected to 129.39.133.102 (129.39.133.102) port 8080 (#0)                                                                                                                       
  * allocate connect buffer!                                                                                                       
  * Establish HTTP proxy tunnel to delivery01-bld.dhe.ibm.com:22                                                                   
  * Server auth using Basic with user 'B80S63'                                                                                     
  > CONNECT delivery01-bld.dhe.ibm.com:22 HTTP/1.1                                                                                 
  > Host: delivery01-bld.dhe.ibm.com:22                                                                                            
  > User-Agent: curl/7.76.1                                                                                                        
  > Proxy-Connection: Keep-Alive                                                                                                   
 >                                                                                                                                
   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 < HTTP/1.1 200 Connection established              
 <                                                                                                                                
 * Proxy replied 200 to CONNECT request                                                                                           
 * CONNECT phase completed!                                                                                                       
 * CONNECT phase completed!                                                                                                       
 * SSH MD5 fingerprint: 44c4200aa7a528e838ed666683119f7f                                                                          
 * SSH authentication methods available: publickey,password                                                                       
 * Using SSH private key file '/home/FR076064/.ssh/id_rsa'                                                                        
   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
 * SSH public key authentication failed: Invalid signature for supplied public key, or bad username/public key combination                                                           
 * Initialized password authentication                                                                                            
 * Authentication complete                                                                                                        
   0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0{ [2336 bytes data]                                
 100  2336  100  2336    0     0    625      0  0:00:03  0:00:03 --:--:--   625                                                   
 100  2336  100  2336    0     0    625      0  0:00:03  0:00:03 --:--:--   625                                                   
 * Connection #0 to host 129.39.133.102 left intact                                                                               
   $
```

Here is the output when ran as a **QSH command**

```
QSH CMD('curl --insecure --proxy "129.39.133.102:8080" --user "B80S63:blabla" --verbose --url sftp://delivery01-bld.dhe.ibm.com/GI/C/ftp1084_1.txt --output /home/fr076064/temp/ftp1084_1.txt')
                   
* About to connect() to proxy 129.39.133.102 port 8080 (#0)                  
*   Trying 129.39.133.102...                                                 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Curre
nt                                                                           
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     
0* connected                                                                 
* Connected to 129.39.133.102 (129.39.133.102) port 8080 (#0)                
* Server auth using Basic with user 'B80S63'                                 
> GET sftp://delivery01-bld.dhe.ibm.com/GI/C/ftp1084_1.txt HTTP/1.1          
> Authorization: Basic QjgwUzYzOk43OFg5THNlZmRMNlVMWQ==                      
> User-Agent: curl/7.27.0                                                    
> Host: delivery01-bld.dhe.ibm.com:22                                        
> Accept: */*                                                                
> Proxy-Connection: Keep-Alive                                               
>                                                                            
< HTTP/1.1 400 Bad Request                                                   
< Server: squid/4.13                                                         
< Mime-Version: 1.0                                                          
< Date: Thu, 14 Oct 2021 15:59:54 GMT                                        
< Content-Type: text/html;charset=utf-8                                      
< Content-Length: 3613                                                       
< X-Squid-Error: ERR_INVALID_URL 0                                           
< Vary: Accept-Language                                                      
< Content-Language: en                                                       
< X-Cache: MISS from fremop2csxprx01                                         
< Connection: close                                                          
<                                                                            
{ [data not shown]                                                           
100  3613  100  3613    0     0   108k      0 --:--:-- --:--:-- --:--:--  113
k                                                                            
* Closing connection #0                                                      
Press ENTER to end terminal session.            
```

**Comment by kadler** [comment]
Do you have a different version of curl installed (maybe from 5733-OPS or AIX rpms)? The default PATH for QSH does not include /QOpenSys/pkgs/bin. You could try fully qualifying it to make sure:
 
QSH CMD('/QOpenSys/pkgs/bin/curl --insecure --proxy ...')
 
Also, I hope that's not your real userid/password you just posted to the list. If so, you probably want to change that...
 
----- Original message -----From: "MarcRauzier" ***@***.***>To: "IBM/ibmi-oss-issues" ***@***.***>Cc: "Subscribed" ***@***.***>Subject: [EXTERNAL] [IBM/ibmi-oss-issues] curl does work the same way when ran from a QSH or ssh session compared when ran as a QSH command (#7)Date: Thu, Oct 14, 2021 11:07 AM      I want to download files from IBM site (PTFs ISO file) using curl from an IBM i partition through a proxy server using sftp. It work fine when initiate the curl command from an interactive QSH or ssh session. But it does not work when I embed    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
I want to download files from IBM site (PTFs ISO file) using curl from an IBM i partition through a proxy server using sftp. It work fine when initiate the curl command from an interactive QSH or ssh session. But it does not work when I embed the curl command in QSH.
Maybe this is a shell syntax issue but I cannot figure where is my error.
Here is the output of curl command when ran through an ssh or QSH session:
  $                                                                                                                                > curl --insecure --proxy "129.39.133.102:8080" --user "B80S63:N78X9LsefdL6ULY" --verbose --url sftp://delivery01-bld.dhe.ibm.com/GI/C/ftp1084_1.txt --output /home/fr076064/temp/ftp1084.txt  *   Trying 129.39.133.102:8080...                                                                                                    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                     Dload  Upload   Total   Spent    Left  Speed                                                        0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  * Connected to 129.39.133.102 (129.39.133.102) port 8080 (#0)                                                                                                                        * allocate connect buffer!                                                                                                        * Establish HTTP proxy tunnel to delivery01-bld.dhe.ibm.com:22                                                                    * Server auth using Basic with user 'B80S63'                                                                                      > CONNECT delivery01-bld.dhe.ibm.com:22 HTTP/1.1                                                                                  > Host: delivery01-bld.dhe.ibm.com:22                                                                                              > User-Agent: curl/7.76.1                                                                                                          > Proxy-Connection: Keep-Alive                                                                                                   >                                                                                                                                   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 < HTTP/1.1 200 Connection established               <                                                                                                                                 * Proxy replied 200 to CONNECT request                                                                                           * CONNECT phase completed!                                                                                                       * CONNECT phase completed!                                                                                                       * SSH MD5 fingerprint: 44c4200aa7a528e838ed666683119f7f                                                                           * SSH authentication methods available: publickey,password                                                                       * Using SSH private key file '/home/FR076064/.ssh/id_rsa'                                                                           0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0 * SSH public key authentication failed: Invalid signature for supplied public key, or bad username/public key combination                                                           * Initialized password authentication                                                                                             * Authentication complete                                                                                                           0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0{ [2336 bytes data]                                 100  2336  100  2336    0     0    625      0  0:00:03  0:00:03 --:--:--   625                                                   100  2336  100  2336    0     0    625      0  0:00:03  0:00:03 --:--:--   625                                                   * Connection #0 to host 129.39.133.102 left intact                                                                                 $
Here is the output when ran as a QSH command
QSH CMD('curl --insecure --proxy "129.39.133.102:8080" --user "B80S63:N78X9LsefdL6ULY" --verbose --url sftp://delivery01-bld.dhe.ibm.com/GI/C/ftp1084_1.txt --output /home/fr076064/temp/ftp1084_1.txt')                  * About to connect() to proxy 129.39.133.102 port 8080 (#0)                  *   Trying 129.39.133.102...                                                  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                           Dload  Upload   Total   Spent    Left  Speed  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--    0* connected                                                                * Connected to 129.39.133.102 (129.39.133.102) port 8080 (#0)                * Server auth using Basic with user 'B80S63'                                > GET sftp://delivery01-bld.dhe.ibm.com/GI/C/ftp1084_1.txt HTTP/1.1          > Authorization: Basic QjgwUzYzOk43OFg5THNlZmRMNlVMWQ==                      > User-Agent: curl/7.27.0                                                    > Host: delivery01-bld.dhe.ibm.com:22                                        > Accept: */*                                                                > Proxy-Connection: Keep-Alive                                              >                                                                            < HTTP/1.1 400 Bad Request                                                  < Server: squid/4.13                                                        < Mime-Version: 1.0                                                          < Date: Thu, 14 Oct 2021 15:59:54 GMT                                        < Content-Type: text/html;charset=utf-8                                      < Content-Length: 3613                                                      < X-Squid-Error: ERR_INVALID_URL 0                                          < Vary: Accept-Language                                                      < Content-Language: en                                                      < X-Cache: MISS from fremop2csxprx01                                        < Connection: close                                                          <                                                                            { [data not shown]                                                          100  3613  100  3613    0     0   108k      0 --:--:-- --:--:-- --:--:--  113k                                                                            * Closing connection #0                                                      Press ENTER to end terminal session.

**Comment by ThePrez** [comment]
Closing as I think this is resolved. Please reopen (or open a new issue) if this is in error. Thanks!
