### ISSUE TITLE
Fatal Symbol errors in Node.js 16.11.1-1

### ISSUE THREAD

**Issue by andyf0x** [IBM/ibmi-oss-issues#9]
I installed Node16 via YUM today, but this package is having fatal Symbol errors: -

```
$ node -v
Could not load program node:
rtld: 0712-001 Symbol RSA_get0_pss_params was referenced
      from module node(), but a runtime definition
            of the symbol was not found.
rtld: 0712-002 fatal error: exiting.

```

Has anyone else tried installing this version and getting similar errors?

This is our first install of Node 16, and also the first install using the new $releasever specific repos for 7.4, so this *could* be a problem with our setup. However, I downgraded to the prior version of Node16, and this seems OK: -

```
$ yum downgrade nodejs16
...
Removed:
  nodejs16.ppc64 0:16.11.1-1

Installed:
  nodejs16.ppc64 0:16.6.2-1

Complete!

$ node -v
v16.6.2
```

**Comment by ThePrez** [comment]
Does upgrading "libopenssl1_1" help at all? (`yum upgrade libopenssl1_1`)

If not, please open this issue over at https://github.com/nodejs/node

**Comment by andyf0x** [comment]
OK great !! Yes, that has resolved the issue I was having. Thanks Jesse !
